name: Build
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

env:
  UNITY_VERSION: 6000.2.6f2

jobs:
  apk:
    uses: QuestNav/QuestNav/.github/workflows/build-questnav-apk.yml@main
    with:
      unityVersion: ${{ env.UNITY_VERSION }}
    permissions:
      contents: write
      pull-requests: write
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

  lib:
    uses: QuestNav/QuestNav/.github/workflows/build-questnav-lib.yml@main
    with:
      wpilibVersion: '2025.3.2'
      releaseToMaven: false
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}